#ifndef LIBEVENT_NET_SERVICE_LIB_H
#define LIBEVENT_NET_SERVICE_LIB_H

#include "xenon/platform.h"

#ifdef LIBEVENT_NET_SERVICE_AS_DLL
	#if  defined ( LIBEVENT_NET_SERVICE_EXPORT )
	#define LIBEVENT_NET_SERVICE_DECL XE_DLL_EXPORT
	#else
	#define LIBEVENT_NET_SERVICE_DECL XE_DLL_IMPORT
	#endif // LIBEVENT_NET_SERVICE_EXPORT
#else
	#define LIBEVENT_NET_SERVICE_DECL
#endif

#endif // LIBEVENT_NET_SERVICE_LIB_H
