#ifndef COMPONENT_SERVICE_LIB_H
#define COMPONENT_SERVICE_LIB_H

#include "dxm/platform.h"

#ifdef COMPONENT_SERVICE_AS_DLL
	#if  defined ( COMPONENT_SERVICE_EXPORT )
	#define COMPONENT_SERVICE_DECL XE_DLL_EXPORT
	#else
	#define COMPONENT_SERVICE_DECL XE_DLL_IMPORT
	#endif // COMPONENT_SERVICE_EXPORT
#else
	#define COMPONENT_SERVICE_DECL
#endif

#endif // COMPONENT_SERVICE_LIB_H
